/**
 * The wasm-bindgen output is generated by `cargo xtask build-wasm`, so it is
 * absent in a fresh checkout and in the typecheck job. Declaring it keeps the
 * demo typecheckable without making the generated files a prerequisite.
 *
 * Deliberately loose on the class: `WasmBackend` accepts the module
 * structurally, and duplicating the real handle signature here would be a
 * second copy to keep in sync with the Rust.
 */
declare module 'web-slam/pkg/wslam_wasm.js' {
  /** wasm-bindgen's init: fetches and instantiates the module. */
  const init: (input?: unknown) => Promise<unknown>;
  export default init;
  /** The session class. */
  export const WasmSlam: new (configJson: string) => never;
  /** Present only when built with the `gpu` feature. */
  export function acquire_gpu(): Promise<boolean>;
}
