//! AprilTag 36h11 payload layout, rotation algebra and codebook.
//!
//! # Scope limitation — read this before shipping
//!
//! The geometry in this crate (threshold, segmentation, quad fit, homography,
//! decode, pose) is a complete implementation. **The codebook is not the
//! canonical 587-entry `tag36h11` table.** Reproducing that table requires
//! Olson's randomised greedy search over the 2^36 code space, and the published
//! artifact is data, not an algorithm — it cannot be re-derived from its
//! parameters.
//!
//! What is here instead is a *generated* code set with the same parameters as
//! the family: 36 payload bits, a 6x6 data grid inside a one-cell black border,
//! and a minimum Hamming distance of 11 taken over all four rotations of every
//! pair, including each code against its own rotations. [`CODES`] is a frozen
//! table produced by [`generate_codes`], and its distance property is asserted
//! by test rather than asserted in prose.
//!
//! The consequence, stated plainly: **tags printed from the official
//! `tag36h11` family will not decode against this table, and our IDs are not
//! their IDs.** Swapping in the canonical table is a data change —
//! [`Codebook::from_codes`] takes it — and touches no decoding logic. Until
//! that happens, `FiducialScale` works against tags rendered by
//! [`crate::fiducial::render`], which is enough for the synthetic rig and the
//! Tier-1 suite but not for a printed target.

use wslam_core::DeterministicRng;

/// Payload bits in a 36h11 tag.
pub const NBITS: usize = 36;

/// Cells across the black-bordered square: 6 data cells plus one border cell
/// on each side. This square is what the detector's quad outlines, and what
/// `size_meters` measures.
pub const WIDTH_AT_BORDER: usize = 8;

/// Cells across the printed tag including the mandatory white quiet margin.
pub const TOTAL_WIDTH: usize = 10;

/// Minimum Hamming distance of the family, over all four rotations. The `11`
/// in "36h11".
pub const MIN_HAMMING: u32 = 11;

/// Mask covering the 36 payload bits.
pub const CODE_MASK: u64 = (1u64 << NBITS) - 1;

/// Frozen code table, generated by [`generate_codes`] with
/// `generate_codes(128, 1 << 22, 20260801)`.
///
/// Provenance is checked by `generated_table_is_reproducible`, and the distance
/// property by `codebook_has_minimum_hamming_distance_eleven`. See the module
/// docs for why this is not the canonical `tag36h11` table.
pub const CODES: &[u64] = &[
    0xb4740bc51,
    0xd80684291,
    0x66c537116,
    0xb8867aa44,
    0x9d8cab338,
    0xa1492057b,
    0xf578f5ca9,
    0x70f6c9f8d,
    0xa859cfda1,
    0x470225ebf,
    0x144d3d4bb,
    0xf1191573a,
    0xa57a900c5,
    0xdf493317f,
    0x4fc3dc972,
    0x1cedf3c98,
    0xbc2946507,
    0x7f6718312,
    0x692c6e000,
    0x545923eb2,
    0x68949cc03,
    0xd448f5b7d,
    0xbecba74b9,
    0x715a3b7c6,
    0xea9ae6030,
    0x54514a7af,
    0x4baa0c721,
    0x4f0c11cc2,
    0xb9a04b808,
    0x6dacebe75,
    0xb7225d150,
    0x873f06968,
    0xea5cf173b,
    0xc8b945b84,
    0x4b8440374,
    0xad6dca6e9,
    0xc6e15976d,
    0x2d80960ca,
    0xc379306c0,
    0xa6a332fa3,
    0x4939adefd,
    0xd1e636753,
    0x5155f5264,
    0x8c4445894,
    0x4b5a86e05,
    0x5de58aca1,
    0xb8d091669,
    0x578ce4167,
    0xd5d2489b6,
    0x9f70e69a7,
    0xfb735446f,
    0x4769dd0e3,
    0x6f95ca80a,
    0xde6f80bf8,
    0x4d9cbeb14,
    0x4a247c4c6,
    0xb0eb411cf,
    0x5bb83b94a,
    0x885a113ea,
    0xa20cd088d,
    0x811417671,
    0xb5a28fde2,
    0x5c128a621,
    0x3f2414c0d,
    0x9b5c8df79,
    0xc1bde329a,
    0x31db8a197,
    0x159fb210e,
    0x73f0476b5,
    0xd9465a74d,
    0x2bf8d142c,
    0x6bf5f1cb7,
    0x3030381ed,
    0xa95032aa4,
    0xcbfbe9189,
    0x7aeb25ff7,
    0xd2b66f64d,
    0xf4123bba5,
    0x84fbd3a2d,
    0xeeecc0e4d,
    0x7c0c43748,
    0xbb1bba544,
    0x3e7d7d670,
    0xe141eca4e,
    0xdfc7cb29a,
    0x2dc28a90d,
    0x31944a52e,
    0x1656457a6,
    0xb0ad15831,
    0x1df494875,
    0x19539d4ed,
    0x7ca5b915c,
    0x2e5d2b515,
    0x28b52863b,
    0x9b03b08d5,
    0x52ee0a78b,
    0x2c3ae0475,
    0x2cee34061,
    0x7efd47ade,
    0x957f1f625,
    0x8b7d1a1ef,
    0x5c099d393,
    0x256307c77,
    0xcdec970d0,
    0xe7dea5840,
    0x530b3fc95,
    0xbf908ec3b,
    0xe03e19283,
    0xad86d9f81,
    0x7800c0c66,
    0xc4572c315,
    0x5ee2a0a8a,
    0xc620bdb99,
    0x39ab7a738,
    0x83ae37ee5,
    0xaa956dca4,
    0x26fff8a32,
    0x89d93f68f,
    0xe4b605934,
    0x5656792f3,
    0x2d76a18af,
    0x5baccf056,
    0x91519496e,
    0x52da5f1af,
    0x2626185d5,
    0xf22ae81c4,
    0xb72e9a3a8,
    0x54abcd885,
];

/// `(column, row)` of every payload bit inside the 8x8 border square, MSB
/// first.
///
/// Bits spiral inwards in concentric rings — top row left to right, right
/// column top to bottom, bottom row right to left, left column bottom to top —
/// the same layout AprilTag 3 emits for its `h` families. The layout is not
/// cosmetic: a 90-degree rotation of the tag is a cyclic shift within each
/// ring, which is what makes rotation-invariant decoding cheap.
#[must_use]
pub fn bit_positions() -> [(usize, usize); NBITS] {
    let mut out = [(0usize, 0usize); NBITS];
    let mut i = 0;
    for ring in 0..3 {
        let lo = 1 + ring;
        let hi = WIDTH_AT_BORDER - 2 - ring;
        for x in lo..=hi {
            out[i] = (x, lo);
            i += 1;
        }
        for y in (lo + 1)..=hi {
            out[i] = (hi, y);
            i += 1;
        }
        for x in (lo..hi).rev() {
            out[i] = (x, hi);
            i += 1;
        }
        for y in ((lo + 1)..hi).rev() {
            out[i] = (lo, y);
            i += 1;
        }
    }
    debug_assert_eq!(i, NBITS);
    out
}

/// Permutation taking a code to its 90-degree clockwise rotation.
///
/// Rotating the tag image clockwise moves the cell at `(x, y)` to
/// `(W-1-y, x)`, so the rotated code's bit at position `p` is the original
/// code's bit at `(p.y, W-1-p.x)`.
fn rotation_permutation() -> [usize; NBITS] {
    let pos = bit_positions();
    let mut index_of = [[usize::MAX; WIDTH_AT_BORDER]; WIDTH_AT_BORDER];
    for (i, &(x, y)) in pos.iter().enumerate() {
        index_of[y][x] = i;
    }
    let mut perm = [0usize; NBITS];
    for (i, &(x, y)) in pos.iter().enumerate() {
        let (sx, sy) = (y, WIDTH_AT_BORDER - 1 - x);
        perm[i] = index_of[sy][sx];
        debug_assert_ne!(perm[i], usize::MAX, "rotation left the data grid");
    }
    perm
}

#[inline]
fn bit(code: u64, index: usize) -> u64 {
    (code >> (NBITS - 1 - index)) & 1
}

/// Rotate a payload 90 degrees clockwise.
#[must_use]
pub fn rotate90(code: u64) -> u64 {
    let perm = rotation_permutation();
    let mut out = 0u64;
    for (i, &src) in perm.iter().enumerate() {
        out |= bit(code, src) << (NBITS - 1 - i);
    }
    out
}

/// All four rotations of a payload, starting with the payload itself.
#[must_use]
pub fn rotations(code: u64) -> [u64; 4] {
    let r1 = rotate90(code);
    let r2 = rotate90(r1);
    let r3 = rotate90(r2);
    [code, r1, r2, r3]
}

/// Unpack a payload into the 6x6 data grid, indexed `[row][col]` with `true`
/// meaning a white cell.
#[must_use]
pub fn to_grid(code: u64) -> [[bool; 6]; 6] {
    let mut g = [[false; 6]; 6];
    for (i, &(x, y)) in bit_positions().iter().enumerate() {
        g[y - 1][x - 1] = bit(code, i) == 1;
    }
    g
}

/// Inverse of [`to_grid`].
#[must_use]
pub fn from_grid(grid: &[[bool; 6]; 6]) -> u64 {
    let mut code = 0u64;
    for (i, &(x, y)) in bit_positions().iter().enumerate() {
        if grid[y - 1][x - 1] {
            code |= 1u64 << (NBITS - 1 - i);
        }
    }
    code
}

/// Hamming distance between two payloads.
#[inline]
#[must_use]
pub fn hamming(a: u64, b: u64) -> u32 {
    ((a ^ b) & CODE_MASK).count_ones()
}

/// Minimum Hamming distance from `code` to every rotation of every entry in
/// `others`, and to `code`'s own non-identity rotations.
///
/// This is the quantity the "h11" in the family name bounds below.
#[must_use]
pub fn min_distance_over_rotations(code: u64, others: &[u64]) -> u32 {
    let mut best = u32::MAX;
    let rots = rotations(code);
    // Self-rotations: a code that matches its own rotation decodes with an
    // ambiguous orientation, which would silently corrupt the recovered pose.
    for r in &rots[1..] {
        best = best.min(hamming(code, *r));
    }
    for &o in others {
        for r in rotations(o) {
            best = best.min(hamming(code, r));
        }
    }
    best
}

/// Greedily build a code set with the 36h11 distance property.
///
/// Candidates are drawn from a seeded stream (spec.md §6: *"Every RNG is
/// seeded"*) and accepted when [`min_distance_over_rotations`] is at least
/// [`MIN_HAMMING`]. Deterministic: the same `(count, budget, seed)` always
/// produces the same table, which is what makes [`CODES`] auditable.
#[must_use]
pub fn generate_codes(count: usize, candidate_budget: usize, seed: u64) -> Vec<u64> {
    let mut rng = DeterministicRng::new("tag36h11-codebook", seed);
    let mut accepted: Vec<u64> = Vec::with_capacity(count);
    for _ in 0..candidate_budget {
        if accepted.len() == count {
            break;
        }
        // 36 bits from two 32-bit draws' worth of uniform entropy.
        let hi = (rng.uniform() * ((1u64 << 18) as f64)) as u64 & 0x3ffff;
        let lo = (rng.uniform() * ((1u64 << 18) as f64)) as u64 & 0x3ffff;
        let candidate = ((hi << 18) | lo) & CODE_MASK;
        if min_distance_over_rotations(candidate, &accepted) >= MIN_HAMMING {
            accepted.push(candidate);
        }
    }
    accepted
}

/// A decodable set of payloads.
#[derive(Debug, Clone)]
pub struct Codebook {
    codes: Vec<u64>,
    rotations: Vec<[u64; 4]>,
}

/// A payload matched against a [`Codebook`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Match {
    /// Index into the codebook — the tag ID.
    pub id: u32,
    /// Quarter turns the observed payload is rotated relative to the stored
    /// one. Rotating the detected corner list by this many positions puts
    /// corner 0 back on the tag's canonical first corner.
    pub rotation: u8,
    /// Bit errors corrected.
    pub hamming: u32,
}

impl Default for Codebook {
    fn default() -> Self {
        Self::standard()
    }
}

impl Codebook {
    /// The frozen [`CODES`] table.
    #[must_use]
    pub fn standard() -> Self {
        Self::from_codes(CODES)
    }

    /// Build from an explicit table. This is the seam through which the
    /// canonical 587-entry `tag36h11` table drops in as data.
    #[must_use]
    pub fn from_codes(codes: &[u64]) -> Self {
        let codes: Vec<u64> = codes.iter().map(|c| c & CODE_MASK).collect();
        let rotations = codes.iter().map(|&c| rotations(c)).collect();
        Codebook { codes, rotations }
    }

    /// Number of distinct tag IDs.
    #[must_use]
    pub fn len(&self) -> usize {
        self.codes.len()
    }

    /// Whether the codebook is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.codes.is_empty()
    }

    /// The payload for a tag ID.
    #[must_use]
    pub fn code(&self, id: u32) -> Option<u64> {
        self.codes.get(id as usize).copied()
    }

    /// Nearest codebook entry within `max_hamming` bits, over all rotations.
    ///
    /// `max_hamming` is a false-positive control, not an error-correction
    /// budget: the family could correct five bit errors, but every extra bit
    /// of slack multiplies the chance that a random quad in the scene decodes
    /// as a tag. spec.md §5 makes the analogous point for loop closure — a
    /// false positive is worse than no detection at all — and a false fiducial
    /// corrupts scale just as silently.
    #[must_use]
    pub fn lookup(&self, observed: u64, max_hamming: u32) -> Option<Match> {
        let observed = observed & CODE_MASK;
        let mut best: Option<Match> = None;
        for (id, rots) in self.rotations.iter().enumerate() {
            for (rot, &r) in rots.iter().enumerate() {
                let d = hamming(observed, r);
                if d <= max_hamming && best.is_none_or(|b| d < b.hamming) {
                    best = Some(Match {
                        id: id as u32,
                        rotation: rot as u8,
                        hamming: d,
                    });
                }
            }
        }
        best
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn bit_layout_covers_the_six_by_six_data_grid_exactly_once() {
        let pos = bit_positions();
        let unique: HashSet<(usize, usize)> = pos.iter().copied().collect();
        assert_eq!(unique.len(), NBITS);
        for &(x, y) in &pos {
            assert!(
                (1..=6).contains(&x) && (1..=6).contains(&y),
                "({x},{y}) outside data grid"
            );
        }
    }

    #[test]
    fn rotation_permutation_is_a_bijection() {
        let perm = rotation_permutation();
        let unique: HashSet<usize> = perm.iter().copied().collect();
        assert_eq!(unique.len(), NBITS);
    }

    /// The cheap ring-shift rotation must agree with the geometric truth:
    /// unpack to a grid, rotate the grid, repack.
    #[test]
    fn rotate90_matches_an_explicit_grid_rotation() {
        for code in [0x123456789u64, 0xfedcba987, 0x0, CODE_MASK, 0xa5a5a5a5a] {
            let g = to_grid(code & CODE_MASK);
            let mut rotated = [[false; 6]; 6];
            // Clockwise: new[r][c] = old[5-c][r].
            for (r, row) in rotated.iter_mut().enumerate() {
                for (c, cell) in row.iter_mut().enumerate() {
                    *cell = g[5 - c][r];
                }
            }
            assert_eq!(
                rotate90(code & CODE_MASK),
                from_grid(&rotated),
                "code {code:#x}"
            );
        }
    }

    #[test]
    fn four_rotations_return_to_the_original() {
        for code in [0x0u64, CODE_MASK, 0xdeadbeef1, 0x1, 0x800000000] {
            let c = code & CODE_MASK;
            assert_eq!(rotate90(rotate90(rotate90(rotate90(c)))), c);
        }
    }

    #[test]
    fn grid_roundtrip() {
        for code in [0x0u64, CODE_MASK, 0x9e3779b97 & CODE_MASK, 0x555555555] {
            assert_eq!(from_grid(&to_grid(code)), code);
        }
    }

    /// The "h11" in the family name, asserted rather than asserted-in-prose.
    #[test]
    fn codebook_has_minimum_hamming_distance_eleven() {
        assert!(CODES.len() >= 32, "table is suspiciously small");
        let unique: HashSet<u64> = CODES.iter().copied().collect();
        assert_eq!(unique.len(), CODES.len(), "duplicate codes");

        for (i, &c) in CODES.iter().enumerate() {
            let others: Vec<u64> = CODES
                .iter()
                .enumerate()
                .filter(|(j, _)| *j != i)
                .map(|(_, &v)| v)
                .collect();
            let d = min_distance_over_rotations(c, &others);
            assert!(
                d >= MIN_HAMMING,
                "code {i} ({c:#x}) is only {d} bits from another codeword or its own rotation"
            );
        }
    }

    /// The table is reproducible from its stated generator arguments, so its
    /// provenance is checkable rather than asserted.
    #[test]
    fn generated_table_is_reproducible() {
        let regenerated = generate_codes(8, 1 << 22, 20260801);
        assert_eq!(regenerated.len(), 8);
        assert_eq!(&regenerated[..], &CODES[..8]);
    }

    #[test]
    fn lookup_recovers_id_and_rotation_from_a_rotated_payload() {
        let book = Codebook::standard();
        for id in [0u32, 1, 7, 31, (CODES.len() - 1) as u32] {
            let code = book.code(id).unwrap();
            for (rot, observed) in rotations(code).iter().enumerate() {
                let m = book.lookup(*observed, 0).expect("exact payload must match");
                assert_eq!(m.id, id);
                assert_eq!(m.rotation, rot as u8);
                assert_eq!(m.hamming, 0);
            }
        }
    }

    #[test]
    fn lookup_corrects_bit_errors_up_to_the_budget() {
        let book = Codebook::standard();
        let code = book.code(3).unwrap();
        // Flip two bits.
        let corrupted = code ^ 0b101;
        assert_eq!(book.lookup(corrupted, 2).map(|m| m.id), Some(3));
        assert_eq!(book.lookup(corrupted, 2).map(|m| m.hamming), Some(2));
        // ... and refuses when the budget is smaller than the error.
        assert!(book.lookup(corrupted, 1).is_none());
    }

    /// False positives here corrupt scale silently, so a payload that is not a
    /// codeword must not resolve to one. With d = 11 the nearest codeword to a
    /// random payload is 13-18 bits away in practice.
    #[test]
    fn random_payloads_do_not_decode() {
        let book = Codebook::standard();
        let mut rng = DeterministicRng::new("false-positive-probe", 4242);
        let mut hits = 0;
        for _ in 0..20_000 {
            let hi = (rng.uniform() * ((1u64 << 18) as f64)) as u64 & 0x3ffff;
            let lo = (rng.uniform() * ((1u64 << 18) as f64)) as u64 & 0x3ffff;
            if book.lookup(((hi << 18) | lo) & CODE_MASK, 2).is_some() {
                hits += 1;
            }
        }
        assert_eq!(hits, 0, "{hits} random payloads decoded as tags");
    }

    #[test]
    fn empty_codebook_never_matches() {
        let book = Codebook::from_codes(&[]);
        assert!(book.is_empty());
        assert_eq!(book.len(), 0);
        assert!(book.lookup(0, 36).is_none());
        assert!(book.code(0).is_none());
    }
}
